version: 1.0.{build}
image: Visual Studio 2019
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
environment:
  TARGET_CONFIGURATION: Release
build_script:
- cmd: >-
    dotnet build -p:Version=%APPVEYOR_BUILD_VERSION% --configuration %TARGET_CONFIGURATION%
    
    appveyor PushArtifact %APPVEYOR_BUILD_FOLDER%/WoMFramework/bin/Release/WoMFramework.%APPVEYOR_BUILD_VERSION%.nupkg -FileName WoMFramework.%APPVEYOR_BUILD_VERSION%.nupkg -DeploymentName WoMFramework
    
    appveyor PushArtifact %APPVEYOR_BUILD_FOLDER%/WoMWallet/bin/Release/WoMWallet.%APPVEYOR_BUILD_VERSION%.nupkg -FileName WoMWallet.%APPVEYOR_BUILD_VERSION%.nupkg -DeploymentName WoMWallet
    
    dotnet publish %APPVEYOR_BUILD_FOLDER%/WoMSadGui/WoMSadGui.csproj -p:Version=%APPVEYOR_BUILD_VERSION% -c %TARGET_CONFIGURATION% -o ./publish/win-x86 -r win-x86
       
    7z a WoM-%APPVEYOR_BUILD_VERSION%-win-x86.zip %APPVEYOR_BUILD_FOLDER%/publish/win-x86/*

    appveyor PushArtifact WoM-%APPVEYOR_BUILD_VERSION%-win-x86.zip -DeploymentName WoMNetCore
    
    dotnet publish %APPVEYOR_BUILD_FOLDER%/WoMSadGui/WoMSadGui.csproj -p:Version=%APPVEYOR_BUILD_VERSION% --configuration %TARGET_CONFIGURATION% -o ./publish/win-x64 -r win-x64
   
    7z a WoM-%APPVEYOR_BUILD_VERSION%-win-x64.zip %APPVEYOR_BUILD_FOLDER%/publish/win-x64/*

    appveyor PushArtifact WoM-%APPVEYOR_BUILD_VERSION%-win-x64.zip -DeploymentName WoMNetCore

    dotnet publish %APPVEYOR_BUILD_FOLDER%/WoMSadGui/WoMSadGui.csproj -p:Version=%APPVEYOR_BUILD_VERSION% --configuration %TARGET_CONFIGURATION% -o ./publish/linux-x64 -r linux-x64

    7z a WoM-%APPVEYOR_BUILD_VERSION%-linux-x64.zip %APPVEYOR_BUILD_FOLDER%/publish/linux-x64/*

    appveyor PushArtifact WoM-%APPVEYOR_BUILD_VERSION%-linux-x64.zip -DeploymentName WoMNetCore

    dotnet publish %APPVEYOR_BUILD_FOLDER%/WoMSadGui/WoMSadGui.csproj -p:Version=%APPVEYOR_BUILD_VERSION% --configuration %TARGET_CONFIGURATION% -o ./publish/alpine-x64 -r alpine-x64

    7z a WoM-%APPVEYOR_BUILD_VERSION%-alpine-x64.zip %APPVEYOR_BUILD_FOLDER%/publish/alpine-x64/*

    appveyor PushArtifact WoM-%APPVEYOR_BUILD_VERSION%-alpine-x64.zip -DeploymentName WoMNetCore

    dotnet publish %APPVEYOR_BUILD_FOLDER%/WoMSadGui/WoMSadGui.csproj -p:Version=%APPVEYOR_BUILD_VERSION% --configuration %TARGET_CONFIGURATION% -o ./publish/centos-x64 -r centos-x64

    7z a WoM-%APPVEYOR_BUILD_VERSION%-centos-x64.zip %APPVEYOR_BUILD_FOLDER%/publish/centos-x64/*

    appveyor PushArtifact WoM-%APPVEYOR_BUILD_VERSION%-centos-x64.zip -DeploymentName WoMNetCore

    dotnet publish %APPVEYOR_BUILD_FOLDER%/WoMSadGui/WoMSadGui.csproj -p:Version=%APPVEYOR_BUILD_VERSION% --configuration %TARGET_CONFIGURATION% -o ./publish/debian-x64 -r debian-x64

    7z a WoM-%APPVEYOR_BUILD_VERSION%-debian-x64.zip %APPVEYOR_BUILD_FOLDER%/publish/debian-x64/*

    appveyor PushArtifact WoM-%APPVEYOR_BUILD_VERSION%-debian-x64.zip -DeploymentName WoMNetCore

    dotnet publish %APPVEYOR_BUILD_FOLDER%/WoMSadGui/WoMSadGui.csproj -p:Version=%APPVEYOR_BUILD_VERSION% --configuration %TARGET_CONFIGURATION% -o ./publish/fedora-x64 -r fedora-x64

    7z a WoM-%APPVEYOR_BUILD_VERSION%-fedora-x64.zip %APPVEYOR_BUILD_FOLDER%/publish/fedora-x64/*

    appveyor PushArtifact WoM-%APPVEYOR_BUILD_VERSION%-fedora-x64.zip -DeploymentName WoMNetCore

    dotnet publish %APPVEYOR_BUILD_FOLDER%/WoMSadGui/WoMSadGui.csproj -p:Version=%APPVEYOR_BUILD_VERSION% --configuration %TARGET_CONFIGURATION% -o ./publish/gentoo-x64 -r gentoo-x64

    7z a WoM-%APPVEYOR_BUILD_VERSION%-gentoo-x64.zip %APPVEYOR_BUILD_FOLDER%/publish/gentoo-x64/*

    appveyor PushArtifact WoM-%APPVEYOR_BUILD_VERSION%-gentoo-x64.zip -DeploymentName WoMNetCore

    dotnet publish %APPVEYOR_BUILD_FOLDER%/WoMSadGui/WoMSadGui.csproj -p:Version=%APPVEYOR_BUILD_VERSION% --configuration %TARGET_CONFIGURATION% -o ./publish/opensuse-x64 -r opensuse-x64

    7z a WoM-%APPVEYOR_BUILD_VERSION%-opensuse-x64.zip %APPVEYOR_BUILD_FOLDER%/publish/opensuse-x64/*

    appveyor PushArtifact WoM-%APPVEYOR_BUILD_VERSION%-opensuse-x64.zip -DeploymentName WoMNetCore

    dotnet publish %APPVEYOR_BUILD_FOLDER%/WoMSadGui/WoMSadGui.csproj -p:Version=%APPVEYOR_BUILD_VERSION% --configuration %TARGET_CONFIGURATION% -o ./publish/rhel-x64 -r rhel-x64

    7z a WoM-%APPVEYOR_BUILD_VERSION%-rhel-x64.zip %APPVEYOR_BUILD_FOLDER%/publish/rhel-x64/*

    appveyor PushArtifact WoM-%APPVEYOR_BUILD_VERSION%-rhel-x64.zip -DeploymentName WoMNetCore

    dotnet publish %APPVEYOR_BUILD_FOLDER%/WoMSadGui/WoMSadGui.csproj -p:Version=%APPVEYOR_BUILD_VERSION% --configuration %TARGET_CONFIGURATION% -o ./publish/ubuntu-x64 -r ubuntu-x64

    7z a WoM-%APPVEYOR_BUILD_VERSION%-ubuntu-x64.zip %APPVEYOR_BUILD_FOLDER%/publish/ubuntu-x64/*

    appveyor PushArtifact WoM-%APPVEYOR_BUILD_VERSION%-ubuntu-x64.zip -DeploymentName WoMNetCore

    dotnet publish %APPVEYOR_BUILD_FOLDER%/WoMSadGui/WoMSadGui.csproj -p:Version=%APPVEYOR_BUILD_VERSION% --configuration %TARGET_CONFIGURATION% -o ./publish/osx-x64 -r osx-x64

    7z a WoM-%APPVEYOR_BUILD_VERSION%-osx-x64.zip %APPVEYOR_BUILD_FOLDER%/publish/osx-x64/*

    appveyor PushArtifact WoM-%APPVEYOR_BUILD_VERSION%-osx-x64.zip -DeploymentName WoMNetCore
    
test_script:
- cmd: >-
    dotnet test --configuration Release ./WoMFrameworkTest

    dotnet test --configuration Release ./WoMWalletTest
    
deploy:
- provider: NuGet
  api_key:
    secure: qR9SWQUPkiYwFQKvljIajuoDvjS4rDAHkYVY1QaFP3yRqRoEp+LF/Um2v2Y4LqcN
  artifact: /.*.nupkg/
